server:
  port: 8080
  address: "0.0.0.0:8080"

database:
  dbname: "postgres"
  dbuser: "app"
  dbpassword: "dbpassword"
  dbhost: "localhost"
  dbport: 5432
  dbtype: "postgres"

# EXAMPLE_VAR: "variable from config.yml"
# EXAMPLE_PATH: "path from config.yml"